spec:
  template:
    spec:
      containers:
        - envFrom:
          - secretRef:
              name: actracker-api-postgres-app-secret
          - secretRef:
              name: actracker-api-postgres-owner-secret
          - secretRef:
              name: actracker-api-rabbitmq-secret
          - configMapRef:
              name: actracker-api-config
          ports:
            - containerPort: 8080
              name: http
      imagePullSecrets:
        - name: equino-registry