spring:
  profiles:
    group:
      default:
        - 'actracker-api-db-h2'
      dev:
        - 'actracker-api-db-postgres'
      int:
        - 'actracker-api-db-postgres'
      prod:
        - 'actracker-api-db-postgres'
  flyway:
    enabled: false
  h2:
    console.enabled: true # http://localhost:8080/h2-console
server:
  servlet:
    context-path: /actracker-api
