spring:
  profiles:
    group:
      default:
        - 'actracker-api-db-postgres'
      dev:
        - 'actracker-api-db-postgres'
      int:
        - 'actracker-api-db-postgres'
      prod:
        - 'actracker-api-db-postgres'
  flyway:
    enabled: false
server:
  servlet:
    context-path: /actracker-api
