spring:
  flyway:
    enabled: false
  profiles:
    group:
      default:
        - 'actracker-api-db-h2'
      dev:
        - 'actracker-api-db-postgres'
server:
  servlet:
    context-path: /actracker-api
