spring:
  profiles:
    group:
      default:
        # DB
        - 'actracker-api-db-h2'
#        - 'actracker-api-db-postgres'

        # MESSAGING
        - 'actracker-api-publisher-rabbitmq'
#        - 'actracker-api-publisher-memory'
      dev:
        - 'actracker-api-db-postgres'
        - 'actracker-api-publisher-rabbitmq'
      int:
        - 'actracker-api-db-postgres'
        - 'actracker-api-publisher-rabbitmq'
      prod:
        - 'actracker-api-db-postgres'
        - 'actracker-api-publisher-rabbitmq'
  flyway:
    enabled: false
  h2:
    console.enabled: true # http://localhost:8080/h2-console
server:
  servlet:
    context-path: /actracker-api
