spring:
  profiles:
    group:
      default:
        # DB
        - 'actracker-api-db-h2'
        #        - 'actracker-api-db-postgres'

        # MESSAGING
        #        - 'actracker-api-publisher-rabbitmq'
        - 'actracker-api-publisher-memory'
      dev:
        - 'actracker-api-db-postgres'
        - 'actracker-api-publisher-rabbitmq'
      int:
        - 'actracker-api-db-postgres'
        - 'actracker-api-publisher-rabbitmq'
      prod:
        - 'actracker-api-db-postgres'
        - 'actracker-api-publisher-rabbitmq'
  flyway:
    enabled: false
  h2:
    console.enabled: true # http://localhost:8080/h2-console
server:
  servlet:
    context-path: /actracker-api
management:
  endpoints:
    web:
      base-path: /info
      exposure:
        include: "health,metrics,prometheus"
  metrics:
    distribution:
      percentiles:
        all: 0.5, 0.75, 0.95, 0.99
      percentile-histogram:
        all: true
#logging:
#  level:
#    org.springframework.orm.jpa: DEBUG
#    org.springframework.transaction: DEBUG
#    org.hibernate.engine.transaction: DEBUG