name: Build PR

on: pull_request

concurrency: actracker-api-PR

jobs:
  BuildPR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
      - name: Build and test
        run: |
          ./gradlew --no-daemon --stacktrace clean build test
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.EQUINO_REGISTRY_USERNAME }}
          password: ${{ secrets.EQUINO_REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./build/resources/main/docker/Dockerfile
          push: true
          tags: registry.cloud.equino.ovh/actracker-api:0.0.2