name: Release PR
on:
  pull_request:
    types: [ labeled ]

jobs:
  ReleasePR:
    if: ${{ github.event.label.name == 'RELEASE' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: git branch
        run: |
          git branch